# Generated by Django 4.2.5 on 2023-09-22 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('docs', 'Docs'), ('video', 'Video'), ('audio', 'Audio')], default='text', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent_message', models.ForeignKey(blank=True, limit_choices_to={'parent_message': None}, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.messagerecord')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sender'], name='chat_messag_sender__43da4b_idx'), models.Index(fields=['receiver'], name='chat_messag_receive_d56900_idx'), models.Index(fields=['created_at'], name='chat_messag_created_bf728a_idx')],
            },
        ),
    ]
